let numCows = 50;
const x = ("Hello World");
console.log("Hello World");
alert("Hello WOrld");
const numUmbrellas = 10 * 3;
const num = 5 + 1;
alert(num);
const str = 'Hello' + ' ' + 'World';
let str1 = 'Hello';
let str2 = 'I am';
let nombre = 'Josh';
alert(str1 + " " + str2 + " " + nombre);